version: 2

jobs:
  java-base-test: &java-base-test
    working_directory: ~/analytics-java
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: maven-dep-cache-{{ checksum "pom.xml" }}
      - run: mvn test
      - run: mvn package -B
      - run: .buildscript/e2e.sh
      - save_cache:
          key: maven-dep-cache-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - persist_to_workspace:
          root: .
          paths: [.]

  test-jdklatest:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk

  test-jdk10:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:10-jdk-browsers

  test-jdk9:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:9-jdk-browsers

  test-jdk8:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:8-jdk-browsers

  test:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:8-jdk-browsers

  publish:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      CIRCLE_JDK_VERSION: oraclejdk8
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: .buildscript/deploy_snapshot.sh

workflows:
  version: 2
  multi-test:
    jobs:
      - test-jdklatest
      - test-jdk10
      - test-jdk9
      - test-jdk8
  test_and_publish:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
