version: 2

orbs:
  snyk: snyk/snyk@0.0.12

jobs:
  java-base-test: &java-base-test
    working_directory: ~/analytics-java
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: maven-dep-cache-{{ checksum "pom.xml" }}
      - run: mvn spotless:check animal-sniffer:check test verify
      - run:
          name: Test Failed
          when: on_fail
          command: |
            wget https://raw.githubusercontent.com/segmentio/circleci-notifications/master/slack-notify-branch.sh
            chmod u+x slack-notify-branch.sh
            BUILD_STATUS="Failed" NOTIFY_BRANCH="master" ./slack-notify-branch.sh
      - run: mvn package -B
      - save_cache:
          key: maven-dep-cache-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - persist_to_workspace:
          root: .
          paths: [.]

  test-jdklatest:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk

  test-jdk15:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:15-jdk-browsers

  test-jdk14:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:14-jdk-browsers

  test-jdk13:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:13-jdk-browsers

  test-jdk12:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:12-jdk-browsers

  test-jdk11:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:11-jdk-browsers

  test-jdk10:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:10-jdk-browsers

  test-jdk9:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:9-jdk-browsers

  test-jdk8:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:8-jdk-browsers

  test:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:8-jdk-browsers

  publish:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      CIRCLE_JDK_VERSION: oraclejdk8
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: .buildscript/deploy_snapshot.sh

  coverage:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: mvn cobertura:cobertura
      - run: bash <(curl -s https://codecov.io/bash)

  e2e:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: .buildscript/e2e.sh

  snyk:
    <<: *java-base-test
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run:
          name: Snyk
          command: curl -sL https://raw.githubusercontent.com/segmentio/snyk_helpers/master/initialization/snyk.sh | sh
          environment:
            SNYK_FAIL_ON: upgradable
            SNYK_SEVERITY_THRESHOLD: high

workflows:
  version: 2
  multi-test:
    jobs:
      - test-jdklatest
      - test-jdk15
      - test-jdk14
      - test-jdk13
      - test-jdk12
      - test-jdk11
      - test-jdk10
      - test-jdk9
      - test-jdk8
  static_analysis:
    jobs:
      - test
      - coverage:
          requires:
            - test
      - snyk:
          context: snyk
          requires:
            - test
  test_and_publish:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
  scheduled_e2e_test:
    triggers:
      - schedule:
          cron: "5 * * * *"
          filters:
            branches:
              only:
                - master
                - scheduled_e2e_testing
    jobs:
      - test
      - e2e:
          requires:
            - test
